# Generated by Django 3.1.2 on 2020-12-12 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20201130_2132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(max_length=20)),
                ('value_id', models.CharField(help_text='use unique characters, maximum is two', max_length=2)),
                ('discount_price', models.FloatField(blank=True)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'add ons',
            },
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('discount_price', models.FloatField(blank=True)),
                ('tray_name', models.CharField(choices=[('B', 'BREAKFAST'), ('L', 'LUNCH'), ('D', 'DINNER')], max_length=1)),
                ('tray_type', models.CharField(choices=[('M', 'Mini'), ('S', 'Standard'), ('J', 'Jumbo')], max_length=1)),
                ('price', models.FloatField()),
                ('food_items', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrayAddOns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('add_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_curator.addons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tray add_ons',
            },
        ),
        migrations.CreateModel(
            name='TrayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('add_ons', models.ManyToManyField(to='gift_curator.TrayAddOns')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_curator.tray')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrayCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('tray_item', models.ManyToManyField(to='gift_curator.TrayItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('gift_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=10, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('gift_item', models.ManyToManyField(to='gift_curator.GiftItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'GiftBoxes',
            },
        ),
    ]
