# Generated by Django 3.1.2 on 2020-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(max_length=20)),
                ('value_id', models.CharField(default='C', max_length=2)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'add ons',
            },
        ),
    ]
