# Generated by Django 3.1.2 on 2020-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trayaddons_add_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='value_id',
            field=models.CharField(max_length=2),
        ),
    ]
