# Generated by Django 3.1.2 on 2020-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201128_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='value_id',
            field=models.CharField(help_text='use unique characters, maximum is two', max_length=2),
        ),
    ]
