# Generated by Django 3.1.2 on 2020-11-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201128_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftbox',
            name='gift_item',
        ),
        migrations.RemoveField(
            model_name='giftbox',
            name='user',
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='gift_item',
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trayaddons',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='trayaddons',
            name='user',
        ),
        migrations.RemoveField(
            model_name='traycart',
            name='tray_item',
        ),
        migrations.RemoveField(
            model_name='traycart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trayitem',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='trayitem',
            name='tray',
        ),
        migrations.RemoveField(
            model_name='trayitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddOns',
        ),
        migrations.DeleteModel(
            name='GiftBox',
        ),
        migrations.DeleteModel(
            name='GiftItem',
        ),
        migrations.DeleteModel(
            name='Tray',
        ),
        migrations.DeleteModel(
            name='TrayAddOns',
        ),
        migrations.DeleteModel(
            name='TrayCart',
        ),
        migrations.DeleteModel(
            name='TrayItem',
        ),
    ]
