# Generated by Django 3.1.2 on 2020-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
