# Generated by Django 3.1.2 on 2020-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=100),
        ),
    ]
