# Generated by Django 3.1.2 on 2020-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201029_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.SlugField(max_length=15),
        ),
    ]
