# Generated by Django 3.1.2 on 2020-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201029_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
