# Generated by Django 3.1.2 on 2020-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='product_images/default-01.jpg', upload_to=''),
        ),
    ]
