# Generated by Django 3.1.2 on 2020-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.CharField(blank=True, choices=[('F', '16inches'), ('S', '18inches'), ('T', '20inches')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='Should be a unique name of the product'),
        ),
    ]
