# Generated by Django 3.1.2 on 2020-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201105_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
    ]
