# Generated by Django 3.1.2 on 2020-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201105_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.CharField(blank=True, choices=[('F', '16inches'), ('S', '18inches'), ('T', '20inches')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='product_images/default-01.jpg', upload_to=''),
        ),
    ]
