# Generated by Django 3.1.2 on 2020-11-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_auto_20201106_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trays',
            options={'verbose_name_plural': 'Trayes'},
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='gift_tray',
        ),
        migrations.CreateModel(
            name='GiftTray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('gift_tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
