# Generated by Django 3.1.2 on 2020-11-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201106_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftbox',
            old_name='GiftItem',
            new_name='gift_item',
        ),
    ]
